### ISSUE TITLE
Open Korean Text 2.3.0으로 사용했을 때의 오류 

### ISSUE THREAD

**Issue by huklee** [cookieshake/pyokt#1]
해당 코드에서 최신 버전의 Open Korean Text를 사용하려고 하니 문제가 발생했습니다.
OpenKoreanText의 원본을 가지고 와서 mvn package로 jar를 만들어서 pyokt/jars에 집어넣었습니다.
그 이후에 사용해 보니, java.lang.IncompatibleClassChangeErrorPyRaisable가 뜨네요.

혹시 최신 버전에서의 문제인가 싶어서 예전 버전(2.0.2)을 기준으로 소스로 똑같이 mvn package해서 나온 target 폴더의 jar 파일을 써봤는데도 같은 결과가 나오네요. (https://github.com/open-korean-text/open-korean-text/tree/f269b500b92789c95ec6e71803766facb1d2405b)

OKT에서 빌드를 할 때 뭔가 조건을 따로 주어서 한다던가 하는 것이 필요한 지 궁금합니다. 참고로 저는 ubuntu 16.0.4, openjdk version "1.8.0_171" 환경에서 진행하였습니다.

* 파일 Tree 구조

├── pyokt
│   ├── __init__.py
│   ├── jars
│   │   ├── open-korean-text-2.3.0.jar
│   │   ├── pyokt.jar
│   │   ├── scala-library-2.12.2.jar
│   │   └── twitter-text-1.14.3.jar
│   ├── java
│   │   └── net
│   │       └── ingtra
│   │           └── pyokt
│   │               └── OpenKoreanTextWrapper.java
│   ├── __pycache__
│   │   ├── __init__.cpython-35.pyc
│   │   └── util.cpython-35.pyc
│   └── util.py
├── README.md

* 오류내용 

In [1]: import pyokt

In [2]: pyokt.tokenize("안녕하세요")
---------------------------------------------------------------------------
java.lang.IncompatibleClassChangeErrorPyRaisableTraceback (most recent call last)
<ipython-input-2-b9cc0ed2d902> in <module>()
----> 1 pyokt.tokenize("안녕하세요")

/home/h_uk.lee/work/pyokt/pyokt/__init__.py in tokenize(text, nomalize, stem)
     39 def tokenize(text, nomalize=False, stem=False):
     40     okt = load_okt()
---> 41     tokenized = okt.tokenize(text, java_bool(nomalize), java_bool(stem))
     42
     43     return [KoreanToken(t) for t in tokenized]

java.lang.IncompatibleClassChangeErrorPyRaisable: java.lang.NoSuchMethodError: org.openkoreantext.processor.KoreanTokenJava.<init>(Ljav
a/lang/String;Lorg/openkoreantext/processor/KoreanPosJava;IIZ)V

**Comment by cookieshake** [comment]
오랫동안 github을 사용하지 않아 답변이 늦었습니다. 

pyokt는 pyokt.jar 내부에 있는 java-wrapper(OpenKoreanTextWrapper)를 jpype로 호출하는 구조로 되어있는데, OKT 버전 업데이트로 인해 java-wrapper에서 호출하는 OKT의 메소드에 변경이 생긴 것 같습니다.

정말 상기 이유 때문인지는 알아보아야 할 것 같고, 이유를 알아내면 말씀드림과 동시에 버전업데이트 진행하도록 하겠습니다.

**Comment by cookieshake** [comment]
@huklee 버전 업데이트 완료하였습니다
